Add responders gem
The test said view was missing, so
I want the create method to respond with
json object, so I added responders gem.

Now the error is: "Failure/Error:
expect(idea_response['idea']['title']).to eq('purple pancakes')
     NoMethodError:
            undefined method `[]' for nil:NilClass'`"